name: sqlite_video
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  floor: ^0.13.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  floor_generator: ^0.13.0
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
